/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EnterpriseHead;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EnterpriseHeadOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import static java.time.Clock.system;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ujjwal.garad
 */
public class EnterpriseHeadWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseHeadWorkArea
     */
    
    private JPanel upc;
    private EcoSystem system;
    private UserAccount account;
    private EnterpriseHeadOrganization organization;
    private Enterprise enterprise;
    
    public EnterpriseHeadWorkArea(JPanel userProcessContainer, EcoSystem system, UserAccount account, EnterpriseHeadOrganization organization, Enterprise enterprise) {
        initComponents();
        this.upc = userProcessContainer;
        this.system = system;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        tblMyWorkRequests.setAutoCreateRowSorter(true);
        
        jLabel17.setText(enterprise.getName());
        
        populateMyWorkRequestTable();    
        populateCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void populateCombo(){

        cmbStatus.removeAllItems();
                cmbStatus.addItem("Case Closed");
                cmbStatus.addItem("Cancelled by Police Dept");
                cmbStatus.addItem("Needs Thorough Investigation");
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMyWorkRequests = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCaseNote = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMyReqDetails = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtMyReqAddress = new javax.swing.JTextField();
        btnProcess = new javax.swing.JButton();
        txtStatusReport = new javax.swing.JTextField();
        userimg = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Enterprise Head Work Area");

        tblMyWorkRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Requester", "Receiver", "Status", "Reported Date", "Resolve Date", "ID", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMyWorkRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMyWorkRequestsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMyWorkRequests);

        jLabel7.setText("Address:");

        jLabel3.setText("Msg from Police Officer:");

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Requests requiring thorough investigation:");

        jLabel4.setText("Report Detils:");

        txtCaseNote.setEditable(false);
        txtCaseNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaseNoteActionPerformed(evt);
            }
        });

        jLabel10.setText("Details:");

        txtMyReqDetails.setEditable(false);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Set Status:");

        txtMyReqAddress.setEditable(false);

        btnProcess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/EnterpriseHead/Capture.PNG"))); // NOI18N
        btnProcess.setText("Process Request");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        txtStatusReport.setEditable(false);
        txtStatusReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtStatusReportMouseClicked(evt);
            }
        });
        txtStatusReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(txtMyReqAddress)
                                .addComponent(txtCaseNote, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMyReqDetails)
                            .addComponent(txtStatusReport)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnProcess)
                                .addGap(18, 18, 18)
                                .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMyReqAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMyReqDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStatusReport)
                            .addComponent(txtCaseNote, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        userimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/EnterpriseHead/enterprise head.png"))); // NOI18N

        jLabel16.setText("Enterprise:");

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userimg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userimg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateMyWorkRequestTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblMyWorkRequests.getModel();
        
        dtm.setRowCount(0);
        
        for(WorkRequest request : account.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[7];
            
            row[0] = request.getSender().getEmployee().getName();
            row[1] = request.getReceiver().getUsername();
            row[2] = request.getCaseSatus();
            row[3] = request.getCrimeDate();
            row[4] = request.getResolveDate();
            row[6] = request.getCrimeType();
            row[5] = request;
            dtm.addRow(row);
        }
    }
    
    private void tblMyWorkRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMyWorkRequestsMouseClicked
        // TODO add your handling code here:
        int row = tblMyWorkRequests.getSelectedRow();
        WorkRequest request = (WorkRequest) tblMyWorkRequests.getModel().getValueAt(row, 5);
        String address = request.getReportingAddress();
        String desc = request.getCrimeCase().getCaseNote();

        txtMyReqAddress.setText(address);
        txtCaseNote.setText(desc);
        txtMyReqDetails.setText(request.getCaseDetails());
        txtStatusReport.setText(request.getCrimeCase().getStatusReport());
        //        txtRemarkHosp.setText(request.getRemarkHosp());
        //      txtRemarkFF.setText(request.getRemarkFF());
        //    txtMsgFF.setText(request.getMsgFF());
        //  txtMsgHosp.setText(request.getMsgHosp());
    }//GEN-LAST:event_tblMyWorkRequestsMouseClicked

    private void txtStatusReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusReportActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(true);
        btnProcess.setEnabled(false);
        txtStatusReport.setEditable(true);
        //txtStatusReport.setText("Provide details of the Status Report");
        JOptionPane.showMessageDialog(null,"Please enter Report Details and set the Status");
    }//GEN-LAST:event_btnProcessActionPerformed

    private void txtStatusReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStatusReportMouseClicked
        // TODO add your handling code here:
        //if(btnSave.isEnabled())
        //txtStatusReport.setText("");
        
    }//GEN-LAST:event_txtStatusReportMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(false);
        btnProcess.setEnabled(true);
        
        int row = tblMyWorkRequests.getSelectedRow();     
        WorkRequest request = (WorkRequest) tblMyWorkRequests.getModel().getValueAt(row, 5);
        request.getCrimeCase().setStatusReport(txtStatusReport.getText());
        request.setCaseSatus(String.valueOf(cmbStatus.getSelectedItem()));
        txtStatusReport.setEnabled(false);
        JOptionPane.showMessageDialog(null,"Request processed succesfully");
        populateMyWorkRequestTable();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCaseNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaseNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaseNoteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblMyWorkRequests;
    private javax.swing.JTextField txtCaseNote;
    private javax.swing.JTextField txtMyReqAddress;
    private javax.swing.JTextField txtMyReqDetails;
    private javax.swing.JTextField txtStatusReport;
    private javax.swing.JLabel userimg;
    // End of variables declaration//GEN-END:variables
}
