/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PoliceOfficer;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FirefighterEnterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.PoliceEnterprise;
import Business.Network.Network;
import Business.Organization.FirefighterProcessorOrganization;
import Business.Organization.HospitalProcessorOrganization;
import Business.Organization.Organization;
import Business.Organization.PoliceOfficerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import UserInterface.SystemAdminWorkArea.ManageNetworkJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ujjwal
 */
public class PoliceOfficerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form PoliceOfficerWorkArea
     */
    
    private JPanel userPRocessContainer;
    private EcoSystem system;
    private UserAccount account;
    private PoliceOfficerOrganization organization;
    private Enterprise enterprise;
    
    public PoliceOfficerWorkArea(JPanel userProcessContainer, EcoSystem system, UserAccount account, PoliceOfficerOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userPRocessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        
        lblUserName.setText("Welcome Officer " + account.getEmployee().getName());
        jLabel15.setText(enterprise.getName());
        
        if(account.getIsActive().equals("yes")){
            lblStatus.setText("Active");
            btnActive.setEnabled(false);
            btnInactive.setEnabled(true);
        }else{
            lblStatus.setText("Inactive");
            btnActive.setEnabled(true);
            btnInactive.setEnabled(false);
        }
        
        tblCrimeTable.setAutoCreateRowSorter(true);
        tblMyWorkRequests.setAutoCreateRowSorter(true);
        
        populateCrimeTable();
        populateMyWorkRequestTable();
    }

    
    public void populateCrimeTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblCrimeTable.getModel();
        
        dtm.setRowCount(0);
        for(Network n : system.getNetworkList()){
            for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof PoliceEnterprise){
                    for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                        if(o instanceof PoliceOfficerOrganization){
                            for(WorkRequest request : o.getWorkQueue().getWorkRequestList()){
                
                                Object[] row = new Object[7];
            
                                row[0] = request.getSender().getEmployee().getName();
                                row[1] = request.getReceiver() == null ? null : request.getReceiver().getUsername();
                                row[2] = request.getCaseSatus();
                                row[3] = request.getCrimeDate();
                                row[4] = request.getResolveDate();
                                row[6] = request.getCrimeType();
                                row[5] = request;
            
                                dtm.addRow(row);
            }
            }
            }
            }
        }
        }
    }
    
    public void populateMyWorkRequestTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblMyWorkRequests.getModel();
        
        dtm.setRowCount(0);
        
        for(WorkRequest request : account.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[7];
            
            row[0] = request.getSender().getEmployee().getName();
            row[1] = request.getReceiver().getUsername();
            row[2] = request.getCaseSatus();
            row[3] = request.getCrimeDate();
            row[4] = request.getResolveDate();
            row[6] = request.getCrimeType();
            row[5] = request;
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserName = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDetails = new javax.swing.JTextArea();
        txtAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCrimeTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnAssign = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtMsgHosp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMyWorkRequests = new javax.swing.JTable();
        txtMsgDeptHead = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMyReqDetails = new javax.swing.JTextArea();
        txtRemarkDeptHead = new javax.swing.JTextField();
        txtRemarkFF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtRemarkHosp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMsgFF = new javax.swing.JTextField();
        btnMakeCase = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtMyReqAddress = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnActive = new javax.swing.JButton();
        btnInactive = new javax.swing.JButton();

        lblUserName.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTabbedPane1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N

        jLabel2.setText("Address:");

        txtDetails.setEditable(false);
        txtDetails.setColumns(20);
        txtDetails.setRows(5);
        jScrollPane2.setViewportView(txtDetails);

        txtAddress.setEditable(false);
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        jLabel3.setText("Details:");

        tblCrimeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Requester", "Receiver", "Status", "Reported Date", "Resolve Date", "ID", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCrimeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCrimeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCrimeTable);

        jButton1.setText("Search by ID");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setText("All work requests:");

        btnAssign.setText("Assign this to me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAssign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(355, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(btnAssign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("All Work Requests", jPanel1);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Work requests assigned to me:");

        txtMsgHosp.setEditable(false);

        jLabel12.setText("Msg to Dept Head:");

        tblMyWorkRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Requester", "Receiver", "Status", "Reported Date", "Resolve Date", "ID", "Type"
            }
        ));
        tblMyWorkRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMyWorkRequestsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMyWorkRequests);

        txtMsgDeptHead.setEditable(false);

        txtMyReqDetails.setEditable(false);
        txtMyReqDetails.setColumns(20);
        txtMyReqDetails.setRows(5);
        jScrollPane4.setViewportView(txtMyReqDetails);

        txtRemarkDeptHead.setEditable(false);

        txtRemarkFF.setEditable(false);

        jLabel5.setText("Address:");

        jLabel8.setText("Msg from FF:");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PoliceOfficer/hospital.png"))); // NOI18N
        jButton3.setText("Send to Hospital");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtRemarkHosp.setEditable(false);

        jLabel13.setText("Msg from Dept Head:");

        jLabel7.setText("Msg from Hosp:");

        txtMsgFF.setEditable(false);

        btnMakeCase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PoliceOfficer/link.png"))); // NOI18N
        btnMakeCase.setText("Make Case");
        btnMakeCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeCaseActionPerformed(evt);
            }
        });

        jLabel9.setText("Msg to Hosp:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PoliceOfficer/Fire_Department_3_small_sexy_firefighter.png"))); // NOI18N
        jButton2.setText("Send to Firefighter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtMyReqAddress.setEditable(false);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PoliceOfficer/Capture.PNG"))); // NOI18N
        jButton4.setText("Process Work Request");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Details:");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PoliceOfficer/level-up.png"))); // NOI18N
        jButton5.setText("Send to Dept Head");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel10.setText("Msg to FF:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMsgHosp)
                                            .addComponent(txtMsgFF))
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6))
                                        .addGap(42, 42, 42))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(57, 57, 57)
                                        .addComponent(txtMyReqAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtRemarkFF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                                        .addComponent(txtRemarkHosp, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtRemarkDeptHead)))))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtMsgDeptHead)
                                        .addGap(72, 72, 72))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5)))
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(btnMakeCase, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMyReqAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtRemarkHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRemarkFF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMsgHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMsgFF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMsgDeptHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtRemarkDeptHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(btnMakeCase, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Work Requests", jPanel2);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PoliceOfficer/officer.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jLabel16.setText("Enterprise:");

        jLabel1.setText("Status:");

        lblStatus.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        btnActive.setText("Set Active");
        btnActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActiveActionPerformed(evt);
            }
        });

        btnInactive.setText("Set Inactive");
        btnInactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnActive)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnInactive)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnActive)
                                .addComponent(btnInactive)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblCrimeTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select the work-request first");
            return;
        }
        
        WorkRequest request = (WorkRequest)tblCrimeTable.getValueAt(selectedRow, 5);
        request.setReceiver(account);
        request.setCaseSatus(WorkRequest.Status.WithPoliceDept.getValue());
        
        account.getWorkQueue().getWorkRequestList().add(request);
        populateCrimeTable();
        populateMyWorkRequestTable();
    }//GEN-LAST:event_btnAssignActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
        int row = tblMyWorkRequests.getSelectedRow();     
        
        if (row < 0){
            JOptionPane.showMessageDialog(null,"Please select the work-request first");
            return;
        }
        WorkRequest request = (WorkRequest) tblMyWorkRequests.getModel().getValueAt(row, 5);
        CardLayout layout = (CardLayout)userPRocessContainer.getLayout();
        ProcessWorkRequest pwr = new ProcessWorkRequest(userPRocessContainer, request,account,system, organization, enterprise);
        //MakeCase mk;
        //mk = new MakeCase(account, request, system, organization, (PoliceEnterprise)enterprise);
        userPRocessContainer.add("processWorkRequest",pwr);
        layout.next(userPRocessContainer);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblCrimeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCrimeTableMouseClicked
        // TODO add your handling code here:
        int row = tblCrimeTable.getSelectedRow();
        WorkRequest request = (WorkRequest) tblCrimeTable.getModel().getValueAt(row, 5);
        String address = request.getReportingAddress();
        String desc = request.getCaseDetails();
        
        txtAddress.setText(address);
        txtDetails.setText(desc);
    }//GEN-LAST:event_tblCrimeTableMouseClicked

    private void tblMyWorkRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMyWorkRequestsMouseClicked
        // TODO add your handling code here:
        int row = tblMyWorkRequests.getSelectedRow();
        WorkRequest request = (WorkRequest) tblMyWorkRequests.getModel().getValueAt(row, 5);
        String address = request.getReportingAddress();
        String desc = request.getCaseDetails();
        
        txtMyReqAddress.setText(address);
        txtMyReqDetails.setText(desc);
        txtRemarkHosp.setText(request.getRemarkHosp());
        txtRemarkFF.setText(request.getRemarkFF());
        txtMsgFF.setText(request.getMsgFF());
        txtMsgHosp.setText(request.getMsgHosp());
        txtMsgDeptHead.setText(request.getMsgDeptHead());
        txtRemarkDeptHead.setText(request.getRemarkDeptHead());
    }//GEN-LAST:event_tblMyWorkRequestsMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row = tblMyWorkRequests.getSelectedRow();
        
        if (row < 0){
            JOptionPane.showMessageDialog(null,"Please select the work-request first");
            return;
        }
        
        WorkRequest request = (WorkRequest) tblMyWorkRequests.getModel().getValueAt(row, 5);
        
        String input = JOptionPane.showInputDialog("Please enter the message for Hospital Processor:");
        request.setMsgHosp(input);
        
        int myX = request.getSender().getCurrentLocation().getLocationX();
        int myY = request.getSender().getCurrentLocation().getLocationY();
        int result =150;
        Organization org = null;
        UserAccount resultAccount = null;
        
        for(Network n : system.getNetworkList()){
            for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof HospitalEnterprise){
                    for(Organization o : e.getOrganizationDirectory().getOrganizationList())
                        if(o instanceof HospitalProcessorOrganization){
                            for(UserAccount ua: o.getUserAccountDirectory().getUserAccountList()){
                                if(ua.getIsActive().equals("yes")){
                                int tempX = ua.getCurrentLocation().getLocationX();
                                int tempY = ua.getCurrentLocation().getLocationY();
                                
                                int temp =0;
                                
                                temp =(int) Math.sqrt((myX-tempX)*(myX-tempX) + (myY-tempY)*(myY-tempY));
                                if(temp<result){
                                    result=temp;
                                    org=o;
                                    resultAccount = ua;
                                }
                            }
                            }
//                            request.setCaseSatus("Under Hospital Dept");
                            //o.getWorkQueue().getWorkRequestList().add(request);
                            //populateCrimeTable();
                            //populateMyWorkRequestTable();
                        }
                }
            }
        }
        
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            
            //request.setReceiver(resultAccount);
            //request.setCaseSatus("WithHospital");
            
            
            resultAccount.getWorkQueue().getWorkRequestList().add(request);
            //account.getWorkQueue().getWorkRequestList().add(workRequest);
            JOptionPane.showMessageDialog(null,"Message sent to nearest Hospital Processor!");
            populateCrimeTable();
            //txtAddress.setText("");
            populateMyWorkRequestTable();
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnMakeCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeCaseActionPerformed
        // TODO add your handling code here:
        
        int row = tblMyWorkRequests.getSelectedRow();  
        
        if (row < 0){
            JOptionPane.showMessageDialog(null,"Please select the work-request first");
            return;
        }
        WorkRequest request = (WorkRequest) tblMyWorkRequests.getModel().getValueAt(row, 5);
        CardLayout layout = (CardLayout)userPRocessContainer.getLayout();
        MakeCase mk;
        mk = new MakeCase(userPRocessContainer, account, request, system, organization, (PoliceEnterprise)enterprise);
        userPRocessContainer.add("processWorkRequest",mk);
        layout.next(userPRocessContainer);
    }//GEN-LAST:event_btnMakeCaseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:int row = tblMyWorkRequests.getSelectedRow();
        int row = tblMyWorkRequests.getSelectedRow();
        if (row < 0){
            JOptionPane.showMessageDialog(null,"Please select the work-request first");
            return;
        }
        
        WorkRequest request = (WorkRequest) tblMyWorkRequests.getModel().getValueAt(row, 5);
        
        String input = JOptionPane.showInputDialog("Please enter the message for Firefighter Processor:");
        request.setMsgFF(input);
        
        int myX = request.getSender().getCurrentLocation().getLocationX();
        int myY = request.getSender().getCurrentLocation().getLocationY();
        int result =150;
        Organization org = null;
        UserAccount resultAccount = null;
        
        for(Network n : system.getNetworkList()){
            for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof FirefighterEnterprise){
                    for(Organization o : e.getOrganizationDirectory().getOrganizationList())
                        if(o instanceof FirefighterProcessorOrganization){
                            for(UserAccount ua: o.getUserAccountDirectory().getUserAccountList()){
                                if(ua.getIsActive().equals("yes")){
                                int tempX = ua.getCurrentLocation().getLocationX();
                                int tempY = ua.getCurrentLocation().getLocationY();
                                
                                int temp =0;
                                
                                temp =(int) Math.sqrt((myX-tempX)*(myX-tempX) + (myY-tempY)*(myY-tempY));
                                if(temp<result){
                                    result=temp;
                                    org=o;
                                    resultAccount = ua;
                                }
                            }
                            }
//                            request.setCaseSatus("Under Hospital Dept");
                            //o.getWorkQueue().getWorkRequestList().add(request);
                            //populateCrimeTable();
                            //populateMyWorkRequestTable();
                        }
                }
            }
        }
        
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            
            //request.setReceiver(resultAccount);
            //request.setCaseSatus("WithHospital");
            
            
            resultAccount.getWorkQueue().getWorkRequestList().add(request);
            //account.getWorkQueue().getWorkRequestList().add(workRequest);
            JOptionPane.showMessageDialog(null,"Message sent to nearest Firefighter Processor!");
            populateCrimeTable();
            //txtAddress.setText("");
            populateMyWorkRequestTable();
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        int searchId = Integer.parseInt(txtSearch.getText().trim());
        
        if(txtSearch.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter Crime Id for search");
            return;
        }else{
            
            
            for(Network n : system.getNetworkList()){
                for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
            if(e instanceof PoliceEnterprise){
                for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                    if(o instanceof PoliceOfficerOrganization){
                        for(WorkRequest w: o.getWorkQueue().getWorkRequestList()){
                            if(searchId == w.getWorkReqId()){
                                SearchResult sr = new SearchResult(w, userPRocessContainer,system,account,organization,enterprise,this);
                                userPRocessContainer.add("searchResult", sr);
                                CardLayout layout = (CardLayout) userPRocessContainer.getLayout();
                                layout.next(userPRocessContainer);
                            }
                        }
                    }
                }
            }
                }
            }
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please enter valid input");
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int row = tblMyWorkRequests.getSelectedRow();
        
        if (row < 0){
            JOptionPane.showMessageDialog(null,"Please select the work-request first");
            return;
        }
        
        WorkRequest request = (WorkRequest) tblMyWorkRequests.getModel().getValueAt(row, 5);
        
        String input = JOptionPane.showInputDialog("Please enter the message for Dept Head:");
        request.setMsgDeptHead(input);
        
        for(UserAccount ua : system.getUserAccountDirectory().getUserAccountList()){
                if(!ua.getUsername().equals("sysadmin")){
                    request.setCaseSatus("WithDeptHead");
                    ua.getWorkQueue().getWorkRequestList().add(request);
                    populateCrimeTable();
                    populateMyWorkRequestTable();
                }           
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActiveActionPerformed
        // TODO add your handling code here:
        account.setIsActive("yes");
        lblStatus.setText("Active");
        btnInactive.setEnabled(true);
        btnActive.setEnabled(false);
    }//GEN-LAST:event_btnActiveActionPerformed

    private void btnInactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactiveActionPerformed
        // TODO add your handling code here:
        account.setIsActive("no");
        lblStatus.setText("Inactive");
        btnInactive.setEnabled(false);
        btnActive.setEnabled(true);
    }//GEN-LAST:event_btnInactiveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActive;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnInactive;
    private javax.swing.JButton btnMakeCase;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTable tblCrimeTable;
    private javax.swing.JTable tblMyWorkRequests;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextArea txtDetails;
    private javax.swing.JTextField txtMsgDeptHead;
    private javax.swing.JTextField txtMsgFF;
    private javax.swing.JTextField txtMsgHosp;
    private javax.swing.JTextField txtMyReqAddress;
    private javax.swing.JTextArea txtMyReqDetails;
    private javax.swing.JTextField txtRemarkDeptHead;
    private javax.swing.JTextField txtRemarkFF;
    private javax.swing.JTextField txtRemarkHosp;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}